name: domainchecker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_bloc: 3.2.0
  intl: ^0.16.0
  sqflite: ^1.3.0
  path_provider: ^1.1.0
  progress_dialog: 1.2.1
  fluttertoast: ^3.1.3
  # To open the url
  url_launcher: 5.4.2

  # Used for dependency injection
  get_it: 4.0.1

  #Creates an automated routing class
  auto_route: 0.3.1
  toast: ^0.1.5

  # flutter_platform_widgets will display the widget for both platform seperately
  flutter_platform_widgets: 0.32.4
  equatable: 1.1.1
  wave: ^0.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.6+3

  # A composable, Future-based library for making HTTP requests.
  http: ^0.12.0+2

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4

  #a powerful logging framework
  logger: ^0.8.3

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.0+1

  # A powerful Http client for Dart
  dio: 3.0.8

  # A flexible widget for user notification.
  flushbar: ^1.9.1

  # Material Dialog
  material_dialog: ^0.0.9

  json_annotation: ^3.0.0
  
  getwidget: 

  # GPS Package
  # location: ^3.0.2 
  
  # Using for distance
  # geo: ^0.2.4

  # Notification Library
  # flutter_local_notifications: ^1.4.4+1

  # Searchable Dropdown
  # searchable_dropdown: ^1.1.3

  # search_choices: ^1.0.17

  # photo_view: ^0.9.2

  # image_picker: ^0.6.7+4

  # video_player:

  retrofit: ^1.3.4

  cached_network_image: ^2.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.3.2
  json_serializable: ^3.2.3
  retrofit_generator: ^1.0.1
  # of course build_runner is needed to run the generator
  build_runner: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/logo.png
  #   - assets/images/powered_by.png
  #   - assets/images/login-bg-bl.jpg